name: Deploy G2PK to Server

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04-arm

    steps:
      - uses: actions/checkout@v4

      - name: Build and push Docker image
        run: |
          echo "${{ secrets.DOCKER_LOGIN_PW }}" | docker login -u "${{ secrets.DOCKER_LOGIN_USERNAME }}" --password-stdin
          docker build -t ${{ secrets.DOCKER_LOGIN_USERNAME }}/hangul_diary_flask_g2pk:latest .
          docker push ${{ secrets.DOCKER_LOGIN_USERNAME }}/hangul_diary_flask_g2pk:latest
